### ISSUE TITLE
How do I cite this?

### ISSUE THREAD

**Issue by Sylindril** [mr-easy/GMM-EM-Python#1]
Hi, I found this repo really useful when implementing the EM algorithm for one of my assignments - as we are required to cite all code we refer to, could you please add a citation.cff file so that I can give you the due credit? Until then, I'll use the GitHub repo permalink. Ple

**Comment by mr-easy** [comment]
I am glad you find it useful. I have added a [CITATION.cff](https://github.com/mr-easy/GMM-EM-Python/blob/101517aeddf678308a966b1c77b2253f6e1393e8/CITATION.cff) file.

**Comment by Sylindril** [comment]
Thanks!
